name: flavorbanner
description: Flavor Banner is a package that make easy to configure flavors and add a banner to show info about device
version: 2.0.0
homepage: https://github.com/p02diada/flutter-flavor-banner

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
